### PR TITLE
Kcolor minimizer

### PR DESCRIPTION
**Pull request by robododge**
This K-coloring evaluation functions takes the approach of actually applying the randomly generated array of colors to the nodes in a graph.  It will return a fitness that minimizes the amount of miscolored nodes. 

The current K-coloring Evaluation function does not actually color any nodes and should possibly be removed.

### CODE REVIEW

**Comment by robododge** [comment]
@jlm429 
No conversation, no discussion here, just "close"?  The current k-coloring problem flawed, it does not aim to minimize the amount of adjacent nodes of the same color.  This code achieves it correctly.

**Comment by jlm429** [comment]
I've had similar experiences with other open source projects before (ahem Apache).   I've actually had tickets closed and code stolen with no response! Argh.  I think sometimes it's easier to let trusted people implement changes at the expense of being more inclusive and democratic.  My initial issue was that including a csv folder instead of generating it on the fly as needed seemed kludgy.  My apologies; I should have made that clear.  After reviewing, I think it's ok as it is.  I will reopen and merge!

**Comment by robododge** [comment]
Hi @jlm429 

Thanks for the re-look and taking the merge.   Good point on the csv files, those contain the edge connections for larger node graphs that are used in the example [KColoringMinimizeTest](https://github.com/robododge/ABAGAIL/blob/94362e8b7ccd72ecbabfbdc08b5783e999529525/src/shared/test/KColoringMinimizeTest.java).  In the example KColoringMinimizeTest, I have comments that give the URLs to where each of the test node graphs originated I.e. the example graph from MLrose, or the Peterson graph. Yes, agree the csv files were a dilemma for me, but I didn't like the way abalone had external data files sitting there in the same directory as the test code so opted for the separate directory.  I felt it was hard for users to draw the connection to solving K-coloring on those well-known graph configurations, thus the csv files containing the graphs helps get past that hump.  (Some of the graphs you will see in CS7280 network science)

Additionally, I would like to float the idea of removal of the original [MaxKColorFitnessFunction](https://github.com/pushkar/ABAGAIL/blob/master/src/opt/ga/MaxKColorFitnessFunction.java) and its testing example.   This implementation leads for users/students in the wrong direction actually giving an illogical fitness result that is backwards, leading them to believe higher values of K equate to a more difficult problem.  Where, in reality, lower values of K are always going to be more difficult.  Would you be receptive to another PR for removal of the original MaxKColorFitnessFunction?

**Comment by jlm429** [comment]
That's fine with me.  Maybe the new one should be moved over to the same directory as the other opt problem tests then (/src/opt/test instead of /src/shared/test).

**Comment by robododge** [comment]
Hi John @jlm429 , I just got back around to look into the remaining cleanup of K-coloring.  Sorry I dropped off during the end of the holiday and into the new year.  But, noticed you already did half of the cleanup by moving to to /src/opt/test [Commit 770059ce82](https://github.com/pushkar/ABAGAIL/commit/770059ce82aacf7bc134178022a1142e46558261).  And you added a Jython wrapper as well!  [Commit 8afed80dc](https://github.com/pushkar/ABAGAIL/commit/8afed80dc681aa269d2fd28b4102832c387db70d).  THANKS!

I still think it is worth while to do a little more cleanup, I would like to submit a PR for this:
1.  Removal of erroneous [MaxKColorFitnessFunction](https://github.com/pushkar/ABAGAIL/blob/master/src/opt/ga/MaxKColorFitnessFunction.java)
2.  **Readme-kcoloring.md** - to give usage notes on ABAGAIL K-coloring as a whole.

If you are still on-board with the idea, I can submit in a new PR?

Steve

**Comment by jlm429** [comment]
Sure!

**Pull request merged**
